# Generated by Django 2.2.4 on 2019-09-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueEntrada',
        ),
        migrations.DeleteModel(
            name='EstoqueSaida',
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
            ],
            options={
                'verbose_name': 'Lista (Entrada)',
                'verbose_name_plural': 'Listas (Entradas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido (Saída)',
                'verbose_name_plural': 'Pedidos (Saídas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
    ]
