# Generated by Django 2.2.4 on 2019-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20190926_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='finaliza',
            field=models.DateField(blank=True, null=True, verbose_name='Finaliza em'),
        ),
    ]
