# Generated by Django 2.2.4 on 2019-11-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_estoque_aberto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ('-usuario',)},
        ),
    ]
