# Generated by Django 2.2.4 on 2019-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20191106_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ('-finaliza', 'usuario')},
        ),
        migrations.RemoveField(
            model_name='estoqueitens',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida'), ('f', 'fechamento')], max_length=1),
        ),
    ]
