# Generated by Django 2.2.4 on 2019-08-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ini', models.DateField()),
                ('data_fim', models.DateField()),
                ('publicada', models.BooleanField()),
                ('mensagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('data_ini',),
            },
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.IntegerField(default=1, verbose_name='Limite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Item')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listas.Lista')),
            ],
            options={
                'ordering': ('lista', 'item'),
            },
        ),
    ]
