# Generated by Django 2.2.4 on 2019-08-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_auto_20190802_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlista',
            name='saldo',
            field=models.IntegerField(default=0, verbose_name='Saldo'),
        ),
    ]
