# Generated by Django 2.2.4 on 2019-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_itemlista_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lista',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
