# Generated by Django 2.2.4 on 2019-08-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_auto_20190806_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlista',
            options={'ordering': ('lista', 'item'), 'verbose_name_plural': 'Itens da Lista'},
        ),
    ]
