# Generated by Django 2.2.4 on 2019-08-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retira',
            field=models.BooleanField(default=False),
        ),
    ]
