# Generated by Django 2.2.4 on 2019-08-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20190804_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='coagri',
            field=models.IntegerField(default=0),
        ),
    ]
