# Generated by Django 2.2.4 on 2019-08-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190804_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='coagri',
        ),
    ]
