# Generated by Django 2.2.4 on 2019-08-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_coagri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
    ]
