# Generated by Django 2.2.4 on 2019-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20190804_2113'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.UniqueConstraint(fields=('pedido', 'item'), name='NaoRepetirItememPedido'),
        ),
    ]
