# Generated by Django 2.2.4 on 2019-08-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20190806_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='lista',
            field=models.ForeignKey(limit_choices_to={'ativa': True}, on_delete=django.db.models.deletion.PROTECT, to='listas.Lista'),
        ),
    ]
