# Generated by Django 2.2.4 on 2019-08-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_auto_20190806_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listas.ItemLista'),
        ),
    ]
