# Generated by Django 2.2.4 on 2019-08-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_auto_20190806_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
