# Generated by Django 2.2.4 on 2019-08-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_auto_20190806_1023'),
        ('pedidos', '0012_delete_pedidoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField(default=1, verbose_name='Qtde')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listas.ItemLista')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.UniqueConstraint(fields=('pedido', 'item'), name='NaoRepetirItememPedido'),
        ),
    ]
