# Generated by Django 2.2.4 on 2019-08-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20190806_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='item',
            field=models.ForeignKey(limit_choices_to={'lista_id': 1}, on_delete=django.db.models.deletion.PROTECT, to='listas.ItemLista'),
        ),
    ]
