# Generated by Django 2.2.4 on 2019-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20190806_1459'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('user', 'lista'), name='UmPedidoporCoAgri'),
        ),
    ]
