# Generated by Django 2.2.4 on 2019-08-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_auto_20190806_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name_plural': 'Itens do Pedido'},
        ),
    ]
