# Generated by Django 2.2.4 on 2019-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_auto_20190819_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
    ]
