# Generated by Django 2.2.4 on 2019-09-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_auto_20190915_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='item',
            field=models.ForeignKey(limit_choices_to={'lista_id': 2}, on_delete=django.db.models.deletion.PROTECT, to='listas.ItemLista'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='qtde',
            field=models.IntegerField(default=0, verbose_name='Qtde'),
        ),
    ]
