# Generated by Django 2.2.4 on 2019-09-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_auto_20190915_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='item',
            new_name='item_lista',
        ),
    ]
