# Generated by Django 2.2.4 on 2019-08-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190802_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='partilha',
            name='icone',
            field=models.CharField(max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
