# Generated by Django 2.2.4 on 2019-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partilha_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partilha',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone'),
        ),
    ]
