# Generated by Django 2.2.4 on 2019-08-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190808_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Itens'},
        ),
        migrations.AddField(
            model_name='coagri',
            name='id_cota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Cota'),
        ),
    ]
