# Generated by Django 2.2.4 on 2019-09-15 17:04

import ERP.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190819_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coagri',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AVISO', 'Aviso Prévio'), ('SUSPENSO', 'Suspenso')], default=ERP.core.models.Status('Ativo'), max_length=15, verbose_name='Status'),
        ),
    ]
