# Generated by Django 2.2.4 on 2019-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190915_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('produto',), 'verbose_name_plural': 'Itens'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='produto',
        ),
        migrations.AddField(
            model_name='item',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
            preserve_default=False,
        ),
    ]
