# Generated by Django 2.2.4 on 2019-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191009_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
        ),
    ]
