# Generated by Django 2.2.4 on 2019-11-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191022_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='coagri',
            name='retira',
            field=models.BooleanField(default=False, verbose_name='Retira'),
        ),
    ]
