# Generated by Django 2.2.4 on 2019-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coagri_retira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estoque',
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Preço R$'),
        ),
        migrations.AddField(
            model_name='item',
            name='saldo',
            field=models.IntegerField(default=0, verbose_name='Saldo Atual'),
        ),
    ]
