# Generated by Django 2.2.8 on 2019-12-20 20:34

import ERP.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coagri',
            name='tipo',
            field=models.CharField(blank=True, choices=[('COTISTA', 'Cotista'), ('TRABALHADOR', 'Trabalhador'), ('BOLSISTA', 'Bolsista'), ('APOIADOR', 'Apoiador'), ('PERMUTA', 'Permuta'), ('VOLUNTARIO', 'Voluntário')], default=ERP.core.models.Tipo('Cotista'), max_length=15, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.CharField(max_length=25, unique=True, verbose_name='Item'),
        ),
    ]
