# Generated by Django 3.0.2 on 2020-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191220_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.CharField(max_length=70, unique=True, verbose_name='Item'),
        ),
    ]
